DROP DATABASE IF EXISTS CENITVITAL;
CREATE DATABASE CENITVITAL;

USE CENITVITAL;

INSERT INTO ROLES
(NAME)
VALUES
('ADMIN'),
('GUEST');

INSERT into USERS
(NAME, EMAIL, PASSWORD, USER_ROLE_ID)
VALUES
('AngelNovo', 'info@angelnovo.es', '$2y$12$ayru4ERyHxT4LrsY1WohXOR59fICyPzaXkVcTDTrL.MAKY25hIvzW', 1);
