DROP DATABASE IF EXISTS CENITVITAL;
CREATE DATABASE CENITVITAL;

USE CENITVITAL;

INSERT into USERS
(NAME, EMAIL, PASSWORD)
VALUES
('AngelNovo', 'info@angelnovo.es', '$2y$12$ayru4ERyHxT4LrsY1WohXOR59fICyPzaXkVcTDTrL.MAKY25hIvzW');
